#!/bin/bash -l
#SBATCH -J'BWA_Mem_Align'            # this names the job
#SBATCH --ntasks=1                      # this sets the number of cores we may use
#SBATCH --nodes=1                       # this setst the number of nodes we will use
#SBATCH -o outlog1                       # this will create an output log
#SBATCH -e errlog1                       # this will create an error log
#SBATCH -t 10:00:00                     # this sets the MAX time the job will run (hh:mm:ss)
#SBATCH --mail-user=cmallory@ucsb.edu   # This is asking for email updates
#SBATCH --mail-type ALL                 # This will send updates at every step



reference_genome_path="FULL_PATH_TO_REFERENCe_GENOME" # Full path to the reference genome
fastq_parent_folder="PATH TO PARENT FOLDER OF FASTQ FILES"  # The fastaqfiles .txt can do the minuta but this hsould get the code close
# update this to point to the csv file that contains the names of fastq files you want to analyze
fastq_files_text_path="$SLURM_SUBMIT_DIR""/FASTA_FILES.txt"   #Should update this to only lookq locally

stampy_conda_environment="bwa_environ"



#First run the unpaired script
cd $SLURM_SUBMIT_DIR # THis will set the current direcotry to location that the job was submitted from.    
echo "the current path now is: $SLURM_SUBMIT_DIR"

todays_date=$(date '+%Y-%m-%d_%H-%M-00')
#Make a directoryt o save settings files and setting information
run_results_folder="stampy_alignment_""$todays_date"
mkdir "./""$run_results_folder"


echo "Running file check script"
./check_for_all_files.sh "$reference_genome_path" "$fastq_parent_folder" "$fastq_files_text_path"


# Later edit this list to pass to the single thread file.   for now we run like this
if [ -f $fastq_files_csv_path ]; then
    mapfile -t fastq_files_names < <(awk -F',' '{for(i=1;i<=NF;i++) print $i}' $fastq_files_csv_path)
else
    echo "File path $fastq_files_csv_path does not exist"; exit 1
fi

echo "Okay lets align stuff now!  Submit multiple jobs!"
stampy_in_order_slowly.sh "$reference_genome_path" "$fastq_parent_folder" $fastq_files_names "$run_results_folder" $stampy_conda_environment




/bin/hostname  # This reports what specific node this code is running on!
time mpirun -np $SLURM_NTASKS  ~pcw/vasp # This will report the actual time that was taken to run my script!

echo "Job finished normally"
scancel $SLURM_JOB_ID
