#!/bin/bash -l
#SBATCH -J'BWA_Mem_Align'            # this names the job
#SBATCH --ntasks=1                      # this sets the number of cores we may use
#SBATCH --nodes=1                       # this setst the number of nodes we will use
#SBATCH -o outlog                       # this will create an output log
#SBATCH -e errlog                       # this will create an error log
#SBATCH -t 1:00:00                     # this sets the MAX time the job will run (hh:mm:ss)
#SBATCH --mail-user=cmallory@ucsb.edu   # This is asking for email updates
#SBATCH --mail-type ALL                 # This will send updates at every step

number_of_threads=1  #set equal to the number of threads given the program

reference_genome_path="$SLURM_SUBMIT_DIR""/../bowtie_alignment/fast_q_files/Reference_genomes/Near_complete_2025_non_ncbi_fasta/CMM_BatrDend_JEL423_V3.genome.fasta" # Full path to the reference genome
fastq_parent_folder="$SLURM_SUBMIT_DIR""/../trimm0matic/past_runs/"  # The fastaqfiles .txt can do the minuta but this hsould get the code close
# update this to point to the csv file that contains the names of fastq files you want to analyze
fastq_files_text_path="$SLURM_SUBMIT_DIR""/reduced_trimmo_names_for_debug.txt"   #Should update this to only lookq locally
reference_index_prefix="$SLURM_SUBMIT_DIR""/reference_indexes/near_complete"  #The file path to the index files


default_index_file_path="NO_DEFAULT_DEFINED"



build_index="true"
conda_environ="bwa_environ"

# The paired_check_for_all_files script will create this file if it passes all the checks
# if it exits early then this file won't be created thus I will make the whole script pause!
passed_check_file_confirmation="pass_check_is_true.txt" 



#First run the unpaired script
cd $SLURM_SUBMIT_DIR # THis will set the current direcotry to location that the job was submitted from.    
echo "the current path now is: $SLURM_SUBMIT_DIR"

# maps the text files that we will be using into a single array for use later
if [ -f $fastq_files_text_path ]; then
    mapfile -t fastq_files_names < <(awk -F',' '{for(i=1;i<=NF;i++) print $i}' $fastq_files_text_path)
else
    echo "File path $fastq_files_text_path does not exist"; exit 1
fi

# Checks that all of our files exist!
echo "Running file check script"
./paired_check_for_all_files.sh "$reference_genome_path" "$fastq_parent_folder" "$fastq_files_names" "$passed_check_file_confirmation"

if [ -f "$passed_check_file_confirmation" ]; then
    echo "The pass check file $passed_check_file_confirmation exists so we passed our check function!"
    rm "$passed_check_file_confirmation"
else
    echo "The pass check file $passed_check_file_confirmation does not exist so we did not pass our checks!"
    echo "run failed"
    exit 1
fi


todays_date=$(date '+%Y-%m-%d_%H-%M-00')
#Make a directoryt o save settings files and setting information
run_results_folder="res_bwa_mem_align""$todays_date"
mkdir "./""$run_results_folder"

exit 1

#must first build the index from the reference genome
if $build_index; then
    ./bwa-mem2-2.2.1_x64-linux/bwa-mem2 index -p "$reference_index_prefix" "$reference_genome_path"
    reference_index_path=reference_index_prefix
else
    reference_index_path="$default_index_file_path"
fi

echo "Okay lets align stuff now!  Submit multiple jobs!"
./paired_align_in_order_slowly.sh "$reference_index_path" "$fastq_parent_folder" $fastq_files_names "$run_results_folder" $conda_environ "$number_of_threads"




/bin/hostname  # This reports what specific node this code is running on!
time mpirun -np $SLURM_NTASKS  ~pcw/vasp # This will report the actual time that was taken to run my script!

echo "Job finished normally"
scancel $SLURM_JOB_ID
