#!/bin/bash -l
#SBATCH -J'picard_add_group_names_bwa_seqy'            # this names the job
#SBATCH --ntasks=24                      # this sets the number of cores we may use
#SBATCH --nodes=1                       # this setst the number of nodes we will use
#SBATCH -o bwa_seqy_outlog_add_group                       # this will create an output log
#SBATCH -e bwa_seqy_errlog_add_group                       # this will create an error log
#SBATCH -t 30:00:00                     # this sets the MAX time the job will run (hh:mm:ss)
#SBATCH --mail-user=cmallory@ucsb.edu   # This is asking for email updates
#SBATCH --mail-type ALL                 # This will send updates at every step


sam_files_text_path="$SLURM_SUBMIT_DIR""/bwa_mem-seqy_clean_files.txt"   #Each .txt file should have the full path

save_folder_name_prefix="bwa_seqy"


#First run the unpaired script
cd $SLURM_SUBMIT_DIR # THis will set the current direcotry to location that the job was submitted from.    
echo "the current path now is: $SLURM_SUBMIT_DIR"


./add_the_groups.sh $sam_files_text_path $save_folder_name_prefix


/bin/hostname  # This reports what specific node this code is running on!
time mpirun -np $SLURM_NTASKS  ~pcw/vasp # This will report the actual time that was taken to run my script!

echo "Job finished normally"
scancel $SLURM_JOB_ID


