#!/bin/bash -l
#SBATCH -J'Seqy_clean_paired1'            # this names the job
#SBATCH --ntasks=12                      # this sets the number of cores we may use
#SBATCH --nodes=1                       # this setst the number of nodes we will use
#SBATCH -o outlog1                       # this will create an output log
#SBATCH -e errlog1                       # this will create an error log
#SBATCH -t 10:00:00                     # this sets the MAX time the job will run (hh:mm:ss)
#SBATCH --mail-user=cmallory@ucsb.edu   # This is asking for email updates
#SBATCH --mail-type ALL                 # This will send updates at every step



#We need to set our file path to be where all of our documents are.
# Typically we will submit our slurm.job file from the right directory.  However
# it is probably good to move to the right folder just in case!
#run_files_top_directory="./home/cmallory/Genetic_analysis/bd_genetics_analysis/bowtie_alignment"  # This variable can be changed to hold the directory where stuff is!

output_folder_name="feb_6_clean/"

#First run the unpaired script
cd $SLURM_SUBMIT_DIR # THis will set the current direcotry to location that the job was submitted from.    
echo "the current path now is: $SLURM_SUBMIT_DIR"

todays_date=$(date '+%Y-%m-%d_%H-%M-00')
#Make a directoryt o save settings files and setting information
run_results_folder="seqy_clean_1""$todays_date"
mkdir "./""$output_folder_name/""$run_results_folder"

# update this to point to the csv file that contains the names of fastq files you want to analyze
fastq_files_csv_path="$SLURM_SUBMIT_DIR""/paired_names.txt"   #Should update this to only lookq locally

echo "Running Paired SeqyClean"
./exacute_paired_clean.sh "$todays_date" "$run_results_folder" "$fastq_files_csv_path"

/bin/hostname  # This reports what specific node this code is running on!
time mpirun -np $SLURM_NTASKS  ~pcw/vasp # This will report the actual time that was taken to run my script!

echo "Job finished normally"
scancel $SLURM_JOB_ID
